# Generated by Django 5.2.3 on 2025-07-03 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_sw', models.CharField(max_length=255)),
                ('content_en', models.TextField(blank=True, null=True)),
                ('content_sw', models.TextField(blank=True, null=True)),
                ('node_type', models.CharField(choices=[('user', 'User Education'), ('teacher', 'Teacher Training'), ('parent', 'Parent Training')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='education.contentnode')),
            ],
        ),
    ]
