# Generated by Django 5.2.3 on 2025-07-13 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_contentnode_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contentnode',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
