# Generated by Django 5.2.3 on 2025-07-07 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentNode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_en', models.CharField(max_length=255)),
                ('title_sw', models.CharField(max_length=255)),
                ('node_type', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('content_en', models.TextField(blank=True)),
                ('content_sw', models.TextField(blank=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chatbot.contentnode')),
            ],
        ),
    ]
